name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Build
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="crypto-cli-$tag-win-x64"
          dotnet publish crypto-cli/crypto-cli.csproj -f net5.0 -r win-x64 -c Release -o "$release_name"
          7z a -tzip "${release_name}.zip" "/${release_name}/*"
          rm -r "$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "crypto-cli*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}